// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ekL7Kh4JUFugN7NRwcML5N0UxLYHN5A',
    appId: '1:226837460011:web:57164f27e026f9a729266e',
    messagingSenderId: '226837460011',
    projectId: 'linkmeup-4c623',
    authDomain: 'linkmeup-4c623.firebaseapp.com',
    storageBucket: 'linkmeup-4c623.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKXIf8MtA2tf6iTMS-pCwoiVMpeTIp1qs',
    appId: '1:226837460011:android:a8c0588feadf04ff29266e',
    messagingSenderId: '226837460011',
    projectId: 'linkmeup-4c623',
    storageBucket: 'linkmeup-4c623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDutsEPYEyQ48WL-0R_GuOXhZPxxMewotA',
    appId: '1:226837460011:ios:7537aab0ba5ae69e29266e',
    messagingSenderId: '226837460011',
    projectId: 'linkmeup-4c623',
    storageBucket: 'linkmeup-4c623.firebasestorage.app',
    iosBundleId: 'com.example.linkmeupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDutsEPYEyQ48WL-0R_GuOXhZPxxMewotA',
    appId: '1:226837460011:ios:7537aab0ba5ae69e29266e',
    messagingSenderId: '226837460011',
    projectId: 'linkmeup-4c623',
    storageBucket: 'linkmeup-4c623.firebasestorage.app',
    iosBundleId: 'com.example.linkmeupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-ekL7Kh4JUFugN7NRwcML5N0UxLYHN5A',
    appId: '1:226837460011:web:2bdd64445e39edc529266e',
    messagingSenderId: '226837460011',
    projectId: 'linkmeup-4c623',
    authDomain: 'linkmeup-4c623.firebaseapp.com',
    storageBucket: 'linkmeup-4c623.firebasestorage.app',
  );
}
