// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIOjaxfu14KbLpvKPTlYtHRxgpfEXLqFc',
    appId: '1:913815620809:web:371abd247faa0f75a91118',
    messagingSenderId: '913815620809',
    projectId: 'linkmeup-6855b',
    authDomain: 'linkmeup-6855b.firebaseapp.com',
    storageBucket: 'linkmeup-6855b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL32-86ZYLNuKBEwApxlXdbtVXc4vm9f8',
    appId: '1:913815620809:android:6aff413e3c46b411a91118',
    messagingSenderId: '913815620809',
    projectId: 'linkmeup-6855b',
    storageBucket: 'linkmeup-6855b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4nxWJ4Iaph5l2ESPCDpRyuMF75T8aqZA',
    appId: '1:913815620809:ios:0250a2a09fb4c91fa91118',
    messagingSenderId: '913815620809',
    projectId: 'linkmeup-6855b',
    storageBucket: 'linkmeup-6855b.firebasestorage.app',
    iosBundleId: 'com.example.linkmeupApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4nxWJ4Iaph5l2ESPCDpRyuMF75T8aqZA',
    appId: '1:913815620809:ios:0250a2a09fb4c91fa91118',
    messagingSenderId: '913815620809',
    projectId: 'linkmeup-6855b',
    storageBucket: 'linkmeup-6855b.firebasestorage.app',
    iosBundleId: 'com.example.linkmeupApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIOjaxfu14KbLpvKPTlYtHRxgpfEXLqFc',
    appId: '1:913815620809:web:2da5bf56e00e4015a91118',
    messagingSenderId: '913815620809',
    projectId: 'linkmeup-6855b',
    authDomain: 'linkmeup-6855b.firebaseapp.com',
    storageBucket: 'linkmeup-6855b.firebasestorage.app',
  );
}
